name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build --tag ordle .

      - name: Dump the docker image to a tarball
        run: docker save -o ordle.tar.gz ordle

      - name: Save the tarball as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: ordle-${{ github.sha }}
          path: ./ordle.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the docker tarball
        uses: actions/download-artifact@v2
        with:
          name: ordle-${{ github.sha }}

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Copy and install the tarball on the remote machine
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ls
          scp -o StrictHostKeyChecking=no ordle.tar.gz ordle@${{ secrets.SSH_DEPLOY_HOST }}:/home/ordle/ordle-.tar.gz

      - name: Kill existing ordle service and restart new one
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh -o StrictHostKeyChecking=no ordle@${{ secrets.SSH_DEPLOY_HOST }} "docker load ordle-.tar.gz"
