name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build --tag ordle .

      - name: Dump the docker image to a tarball
        run: docker save -o ordle.tar.gz ordle

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Copy and install the tarball on the remote machine
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -o StrictHostKeyChecking=no ordle.tar.gz ordle@${{ secrets.SSH_DEPLOY_HOST }}:/home/ordle/ordle.tar.gz

      - name: Kill existing ordle service and restart new one
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no ordle@${{ secrets.SSH_DEPLOY_HOST }} << EOF
          set -euf

          echo "Forcefully removing old Ordle image"
          docker image rm ordle --force

          echo "Loading new version of Ordle"
          docker load --input ordle.tar.gz

          echo "Stopping old Ordle container"
          docker stop ordle-production || true

          echo "Removing old Ordle container"
          docker rm ordle-production || true

          echo "Running new Ordle container"
          docker run --name ordle-production --detach --publish 127.0.0.1:3000:3000 --restart always ordle 

          echo "Done!"
          EOF
